---
- name: Show packages
  hosts: demo
  vars:
    my_pkg: vim-common
  tasks:

    - name: Gather Package Facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Show package facts
      ansible.builtin.debug:
        var: ansible_facts['packages']

    - name: Show package facts for "my_pkg"
      ansible.builtin.debug:
        var: ansible_facts['packages'][my_pkg]
      when: my_pkg in ansible_facts['packages']

    - name: Show package version for "my_pkg"
      ansible.builtin.debug:
        var: ansible_facts['packages'][my_pkg][0]['version']
      when: my_pkg in ansible_facts['packages']

    - name: Setting a Fact
      ansible.builtin.set_fact:
        package_info: "{{ ansible_facts['packages']  }}"

    - name: Show package info from registered variable
      ansible.builtin.debug:
        var: package_info

    - name: Loop over packages and display name and version
      ansible.builtin.debug:
        msg: The package is {{ item }} and the version is {{ ansible_facts['packages'][item][0]['version'] }}
      loop: "{{ package_info | list }}"


    - name: Loop over packages and display name and version
      ansible.builtin.debug:
        msg: The package is {{ item }} and the version is {{ ansible_facts['packages'][item][0]['version'] }}
      loop: "{{ package_info | list }}"
      when: my_pkg in item
