---
- name: Create an RPM Report
  hosts: rhel83
  vars:
    var1: Value

  tasks:

####
#### This section is to collect and perform pre-upgrade tasks and checks. It DOES NOT perform any upgrades
####

    - name: List packages to be updated - collect as yum_ouput
      yum:
        list: updates
        update_cache: true
      register: yum_output

    - name: Output list of packages to be updated
      debug:
        #var: yum_ouput
        msg: "{{ yum_output.results | map(attribute='name') | list | sort}}"

    - name: Capture list of packages to be updated in a file
      local_action:
        module: copy
        content: "{{ yum_output.results | map(attribute='name') | list | sort | to_nice_yaml }}"
        dest: packages_to_be_updated.txt

####
#### This section is to perform upgrades and will change the system
####


    - name: Install updates
      yum:
        name: '*'
        update_cache: yes
        state: latest
      become: yes


####
#### This section is to collect and perform post-upgrade tasks and checks
####

    - name: List updated packages with Shell and RPM Command
      shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
      register: result
      args:
        warn: no

    - name: Updated packages
      debug:
        msg="{{ result.stdout_lines | sort | to_nice_yaml }}"

    - name: Capture list of updated packages to a file
      local_action:
        module: copy
        content: "{{ result.stdout_lines | sort | to_nice_yaml }}"
        dest: packages_updated.txt
