---
- name: Demo - Create Custom Facts and Fact Directory
  hosts: servera
  become: true
  tasks:
    - name: Create Custom Fact Directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: directory
        recurse: yes
        owner: root
        group: root

    - name: Create Custom Fact File
      ansible.builtin.copy:
        src: lshw.fact
        dest: /etc/ansible/facts.d/lshw.fact
        mode: u+rx,g+rx,o+rx
